before:
  hooks:
    - go mod tidy
builds:
  - id: darwin-amd64
    main: ./
    binary: conceal
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X conceal/internal/config.Version={{.Version}}
  - id: darwin-arm64
    main: ./
    binary: conceal
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X conceal/internal/config.Version={{.Version}}
  - id: linux-amd64
    main: ./
    binary: conceal
    goos:
      - linux
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/local/lib/pkgconfig
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X conceal/internal/config.Version={{.Version}}
  - id: linux-arm64
    main: ./
    binary: conceal
    goos:
      - linux
    goarch:
      - arm64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/arm64
      - PKG_CONFIG_PATH=/sysroot/linux/arm64/usr/local/lib/pkgconfig
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X conceal/internal/config.Version={{.Version}}
  - id: linux-armhf
    main: ./
    binary: conceal
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X conceal/internal/config.Version={{.Version}}
archives:
  - id: conceal
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
      - linux-armhf
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    wrap_in_directory: true
    files: []
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
